//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/玩家移动/玩家输入.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @玩家输入: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @玩家输入()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""玩家输入"",
    ""maps"": [
        {
            ""name"": ""回合战斗外"",
            ""id"": ""816da9b4-2984-4216-8926-098febe622b0"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""a14bbdd6-63f2-4b94-9846-250891ff08a3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""26846687-2de7-4eb2-a289-ac0100980849"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""93a3124f-51fe-4111-8054-b78d58623c5e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hit"",
                    ""type"": ""Button"",
                    ""id"": ""2bb380be-b703-42e4-913a-e9347b0ac838"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Death"",
                    ""type"": ""Button"",
                    ""id"": ""583c69b6-80cd-447c-a69f-87986a832208"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""任务栏"",
                    ""type"": ""Button"",
                    ""id"": ""a33d8360-4c16-4d0e-a18a-53407edecffb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""交互"",
                    ""type"": ""Button"",
                    ""id"": ""9533d61d-6765-4308-ba47-265879d6c308"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""move"",
                    ""id"": ""08204604-90bd-4210-8f2d-5fba3e36483c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7503893e-9bf2-4a59-82e5-9372ed9f1fb6"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3dcb3db7-cc88-405a-98d4-abe8f988ab01"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e1911237-b2c2-4d3f-bf9b-d06a81622015"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a8ed85e3-a476-48a6-ba9b-a56006d40f64"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1e29be71-23b7-4dff-9b96-74bfa026d1c3"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a81bb68c-5941-482c-a34b-f87821fb5a6a"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f074443-4766-45ab-9bdb-9000bb6d1573"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""d2f41be5-7025-4763-8f11-4b0a4e72ed60"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hit"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""2924d096-79ac-4f1e-9d3c-7ce7c04cefc2"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Hit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""87c23863-e666-4c86-a3e4-f3e63bb6eb4b"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Hit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""645ca0a6-d2a7-4dd0-9e27-9c4f69f036c6"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Death"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""1d9b0c7e-3c73-4cb8-a4eb-5a8cf54d1adc"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Death"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""cbef8f72-80e7-4f13-8285-2d1a98b7d424"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Death"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1821febf-1467-4fef-80c6-458592fb8d6d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""任务栏"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42dddb1b-3920-44fe-9ada-0304e7bb1f6a"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""交互"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": []
        }
    ]
}");
        // 回合战斗外
        m_回合战斗外 = asset.FindActionMap("回合战斗外", throwIfNotFound: true);
        m_回合战斗外_Move = m_回合战斗外.FindAction("Move", throwIfNotFound: true);
        m_回合战斗外_Attack = m_回合战斗外.FindAction("Attack", throwIfNotFound: true);
        m_回合战斗外_Run = m_回合战斗外.FindAction("Run", throwIfNotFound: true);
        m_回合战斗外_Hit = m_回合战斗外.FindAction("Hit", throwIfNotFound: true);
        m_回合战斗外_Death = m_回合战斗外.FindAction("Death", throwIfNotFound: true);
        m_回合战斗外_任务栏 = m_回合战斗外.FindAction("任务栏", throwIfNotFound: true);
        m_回合战斗外_交互 = m_回合战斗外.FindAction("交互", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // 回合战斗外
    private readonly InputActionMap m_回合战斗外;
    private List<I回合战斗外Actions> m_回合战斗外ActionsCallbackInterfaces = new List<I回合战斗外Actions>();
    private readonly InputAction m_回合战斗外_Move;
    private readonly InputAction m_回合战斗外_Attack;
    private readonly InputAction m_回合战斗外_Run;
    private readonly InputAction m_回合战斗外_Hit;
    private readonly InputAction m_回合战斗外_Death;
    private readonly InputAction m_回合战斗外_任务栏;
    private readonly InputAction m_回合战斗外_交互;
    public struct 回合战斗外Actions
    {
        private @玩家输入 m_Wrapper;
        public 回合战斗外Actions(@玩家输入 wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_回合战斗外_Move;
        public InputAction @Attack => m_Wrapper.m_回合战斗外_Attack;
        public InputAction @Run => m_Wrapper.m_回合战斗外_Run;
        public InputAction @Hit => m_Wrapper.m_回合战斗外_Hit;
        public InputAction @Death => m_Wrapper.m_回合战斗外_Death;
        public InputAction @任务栏 => m_Wrapper.m_回合战斗外_任务栏;
        public InputAction @交互 => m_Wrapper.m_回合战斗外_交互;
        public InputActionMap Get() { return m_Wrapper.m_回合战斗外; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(回合战斗外Actions set) { return set.Get(); }
        public void AddCallbacks(I回合战斗外Actions instance)
        {
            if (instance == null || m_Wrapper.m_回合战斗外ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_回合战斗外ActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @Hit.started += instance.OnHit;
            @Hit.performed += instance.OnHit;
            @Hit.canceled += instance.OnHit;
            @Death.started += instance.OnDeath;
            @Death.performed += instance.OnDeath;
            @Death.canceled += instance.OnDeath;
            @任务栏.started += instance.On任务栏;
            @任务栏.performed += instance.On任务栏;
            @任务栏.canceled += instance.On任务栏;
            @交互.started += instance.On交互;
            @交互.performed += instance.On交互;
            @交互.canceled += instance.On交互;
        }

        private void UnregisterCallbacks(I回合战斗外Actions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @Hit.started -= instance.OnHit;
            @Hit.performed -= instance.OnHit;
            @Hit.canceled -= instance.OnHit;
            @Death.started -= instance.OnDeath;
            @Death.performed -= instance.OnDeath;
            @Death.canceled -= instance.OnDeath;
            @任务栏.started -= instance.On任务栏;
            @任务栏.performed -= instance.On任务栏;
            @任务栏.canceled -= instance.On任务栏;
            @交互.started -= instance.On交互;
            @交互.performed -= instance.On交互;
            @交互.canceled -= instance.On交互;
        }

        public void RemoveCallbacks(I回合战斗外Actions instance)
        {
            if (m_Wrapper.m_回合战斗外ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(I回合战斗外Actions instance)
        {
            foreach (var item in m_Wrapper.m_回合战斗外ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_回合战斗外ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public 回合战斗外Actions @回合战斗外 => new 回合战斗外Actions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface I回合战斗外Actions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnHit(InputAction.CallbackContext context);
        void OnDeath(InputAction.CallbackContext context);
        void On任务栏(InputAction.CallbackContext context);
        void On交互(InputAction.CallbackContext context);
    }
}
